### ISSUE TITLE
IBar Control issue BAS Syntax check

### ISSUE THREAD

**Issue by Haemma83** [SAP/ui5-language-assistant#538] opened 2022-12-15 09:53 UTC
Hello,

please see the issue description at:

https://answers.sap.com/questions/13777111/ibar-control-issue-bas-syntax-check.html?childToView=13778110

Thanks!

Regards

Andreas

**Comment by gregorwolf** [comment] 2022-12-16 23:22
Hi @Haemma83,

I would suggest you provide the full description and not only a link. Also you should link to this incident in the original question.

**Comment by MN-public** [comment] 2022-12-27 12:35
Hi @Haemma83,
we would need to have your complete xml file to reproduce the issue. Thanks
Mariana

**Comment by kirilllavrenyukfioneer** [comment] 2023-05-17 08:23
Hi @MN-public,

I have the same issue in the VSCode. The same error is shown: "The "Toolbar" class is under the "subHeader" aggregation and must match the "IBar" type.".
I use sap.m.Toolbar component which implement interface sap.m.IBar.
So, it is also unclear for me what this error mean.

Is there any solution for this since this ticket was opened?

Best regards,
Kirill

**Comment by MN-public** [comment] 2023-05-17 08:41
Hi Kirill,
we would need to have your project or at least a complete xml file and know which min ui5 version you have in the manifest to reproduce the issue. 
If you cannot add your project here due to security reasons, please feel free to open the ticket for the component CA-UX-IDE
Thanks
Mariana

**Comment by MN-public** [comment] 2023-05-24 09:36
Hi @Haemma83, @kirilllavrenyukfioneer,
the issue is reproducible if `"minUI5Version"` in `manifest.json` of your app is set to the oldest supported UI5 version 1.38. It is caused by the missing features in the API of that version while the extension relies on that API for validation.
We will update our coding to fall back to using the API from UI5 v 1.71 for applications with `"minUI5Version"` set to 1.38 or older to avoid this and similar issues. The section [UI5 Version and framework](https://github.com/SAP/ui5-language-assistant/blob/master/packages/vscode-ui5-language-assistant/README.md#ui5-version-and-framework) in the extension overview will be updated accordingly 

In the meantime, as a workaround, you could check if you could set `"minUI5Version"` to the next higher UI5 version 1.71 at least during the design time.
Best Regards
Mariana

**Comment by MN-public** [comment] 2023-05-25 14:09
Hi @Haemma83, @kirilllavrenyukfioneer,
the validation issue is fixed. Feel free to try it out before the official release if you like: https://github.com/SAP/ui5-language-assistant/releases/tag/v4.0.16
Best Regards,
Mariana

**Comment by MN-public** [comment] 2023-06-12 11:18
The fix is delivered, closing the ticket

**Closed by MN-public** 2023-06-12 11:18 UTC
