### ISSUE TITLE
nullable is mistaken for null

### ISSUE THREAD

**Issue by dinurp** [SAP/ui5-language-assistant#735] opened 2024-11-26 04:58 UTC
Any place in an xml view where I have `nullable` constraint defined, UI5 Language Assistant reports an error. It appears from syntax highlighting that it identifies `nullable` as `null`.
Snippet:
```
			<Input id="booleanInput" value="{path: 'Boolean', type: 'sap.ui.model.odata.type.Boolean',
				constraints: {nullable: false}}"/>
```
Error:
```
[{
	"resource": "../a.view.xml",
	"owner": "_generated_diagnostic_collection_name_#5",
	"severity": 8,
	"message": "Expecting --> } <-- but found --> 'null' <--",
	"source": "UI5 Language Assistant",
	"startLineNumber": 38,
	"startColumn": 19,
	"endLineNumber": 38,
	"endColumn": 23
}]
```
Syntax highlighting:
![image](https://github.com/user-attachments/assets/f551d8e5-4173-4561-8179-bc615ed5a82e)

**Comment by marufrasully** [comment] 2024-12-30 05:24
@dinurp thanks for reporting this issue. The issue is fixed and can be tested with [vsix-v4.0.78](https://github.com/SAP/ui5-language-assistant/releases/tag/v4.0.78). The fix will be part of next delivery.

Thanks and best regards

**Closed by marufrasully** 2024-12-30 05:24 UTC
Labels: bug
