### ISSUE TITLE
False error raised about sap.m.Avatar 

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-language-assistant#209] opened 2020-06-24 07:44 UTC
**Issue**
The UI5 Language Assistant raises the following false alert:
>`The "Avatar" name is neither a class name in the "sap.m" namespace nor an aggregation of the "sap.m.FlexBox" class`

**Envirement**
||Version|
|---------|---------|
|SAPUI5| 1.79.1|
|UI5 Language Assistant| 1.2.0|

**Comment by bd82** [comment] 2020-06-24 08:07
Hello.

sap.m.Avatar was added in version 1.73 of UI5.
While this VSCode extension is (currently) hard-coded to use version 1.71.
- https://github.com/SAP/ui5-language-assistant/blob/master/packages/language-server/src/ui5-model.ts#L14

Support for multiple versions should be added n the future, but I don't know when.
In the meanwhile you could attempt to clone this repo, modify the version variable
and rebuild a custom version of the vsix. (yarn ci from the root of the repo).

**Comment by bd82** [comment] 2020-07-08 13:38
I am closing this as it is not a bug but rather a limitation until this extension supports
custom UI5 lib versions.

**Closed** 2020-07-08 13:38 UTC
