### ISSUE TITLE
Hard-coded (1.71.x) version for the SAPUI5 metadata?

### ISSUE THREAD

**Issue by sammok83** [SAP/ui5-language-assistant#521] opened 2022-11-17 06:08 UTC
Hi,

Noticed in the VS Code extension documentation that it's using the hard-coded version of the UI5 metadata as below:
**_SAPUI5 version
This extension currently uses a hard-coded (1.71.x) version for the SAPUI5 metadata._**

However, according to this link: https://github.com/SAP/ui5-language-assistant/tree/master/packages/vscode-ui5-language-assistant
It's specified as below:
**_UI5 version and framework
This extension derives the UI5 version in the following sequence:
the minUI5Version from the manifest.json file
Lookup in CDN for UI5 version and negotiates to the closest LTS version, if not found
Default back to 1.71 (latest patch level)
The framework(SAPUI5/OpenUI5) is derived from the ui5.yaml file. This defaults to SAPUI5._**

I've tried this:
**xmlns:macros="sap.fe.macros"** in one of xml views and I'm getting:
_Unknown namespace: "sap.fe.macros"UI5 Language Assistant_

In my package.json, I've specified this.
"minUI5Version": "1.107.0"

can we specify the UI5 version for this please? Or is not this supported currently?

**Comment by uxkjaer** [comment] 2022-11-17 06:18
Hi.

The new version of the language assistant is reading the different ui5
versions. But we have some limitations in regards to sap.fe.macros. We are
currently reviewing how to incorporate this.

**Comment by jvanattedev** [comment] 2022-12-22 12:02
I can confirm this issue is still a problem, even in projects without sap.fe.macros. minUI5Version is clearly indicated as 1.96.8, but in the bottom right, 1.71.49 is displayed.

**Comment by jvanattedev** [comment] 2022-12-22 13:51
I have been able to reproduce more of this problem:

1. I open a VS Code project with the correct minUI5Version.
2. The UI5 Assistant displays 1.71.49 in an XML View.
3. I then remove that minUI5Version and put it back (just making sure this property has been edited).
4. Then the UI5 Assistant displays the correct version from minUI5Version.

The next time you open VS Code again on this project, the UI5 Assistant displays 1.71.49 again.
So, you can bypass the problem currently, but you have to do this every time.

The version detection is not triggered properly the first time.

**Comment by voicis** [comment] 2023-01-06 12:17
Hi, 

Are you using a workspace with multiple folders?
There was an issue with picking up correct UI5 version in workspace scenario, which is now fixed in master.

**Comment by vadson71** [comment] 2023-01-25 08:06
Hi!

Are you using extension installed from marketplace or master version?
The issue is reproducible in v.3.3.1 which is now available on marketplace but. in master it should be already fixed.

**Comment by jvanattedev** [comment] 2023-01-25 08:31
ok, how do I use the master version? Can I create a .vsix file from the repository for example?

**Comment by vadson71** [comment] 2023-01-25 10:02
Well, please try to perform following steps:
1. Clone language assistant repo to a new local folder - `git clone https://github.com/SAP/ui5-language-assistant.git`
2. Install npm dependencies - `yarn install` at the repo root
3. Launch `yarn ci` at the repo root. This command builds all repo packages
4. As a result in the package `vscode-ui5-language-assistant` the .vsix file should be generated which you can install in the VSCode,

**Comment by jvanattedev** [comment] 2023-01-25 10:30
Thanks for the instructions. The CI seemed to run successfully. But there is nog .vsix file in the folder (ui5-language-assistant) or subfolders.

**Comment by vadson71** [comment] 2023-01-25 10:52
Please check folder <repo root>/packages/vscode-ui5-language-assistant. It should be there.
If no, then try to run command `yarn package` inside this folder. If you see some error please post console output

**Comment by vadson71** [comment] 2023-01-25 10:54
Or you can try `yarn ci` inside the mentioned folder

**Comment by jvanattedev** [comment] 2023-01-25 11:56
That worked. I've been able to install it now.

**Comment by vadson71** [comment] 2023-01-25 12:11
Great! Does this version work fine for you?

**Comment by jvanattedev** [comment] 2023-01-25 12:29
My tests confirm that the validation is now correct. I've sent it to a few other colleagues too for verification.

**Comment by vadson71** [comment] 2023-01-25 14:44
Ok. Please close the ticket when you are sure the issue has been resolved.

**Comment by jvanattedev** [comment] 2023-01-27 07:51
> Ok. Please close the ticket when you are sure the issue has been resolved.

I did not open this issue? Not sure if I can close it.

**Comment by MN-public** [comment] 2023-02-03 09:15
@jvanattedev closing issue for you, thanks for validating

**Closed by MN-public** 2023-02-03 09:15 UTC
