### ISSUE TITLE
ui5-language-assistant

### ISSUE THREAD

**Issue by liorniv** [SAP/ui5-language-assistant#570] opened 2023-02-28 11:37 UTC
Hi

I'm working OFFILNE in VSCODE in SAPUI5 free style applications.
Unfortunately, I can't use the extension ui5-language-assistant in OFFLINE (no connection to INTERNET).
Is there a workaround for autoComplete?  

Unnecessary to mention that without autoComplete, there is no point to use the VSCODE regarding SAPUI5.
SAP OSS says that it will take some time to fix this issue.
Thanks
Lior Niv

**Comment by voicis** [comment] 2023-03-08 10:22
This looks like a duplicate of #520.

**Comment by MN-public** [comment] 2023-03-08 13:15
@liorniv 
Thanks for bringing this up. This looks indeed as a duplicate of https://github.com/SAP/ui5-language-assistant/issues/520.
We are now looking into implementing the possibility of offline work with UI5 Language Assistant and will provide the updates/fixes for the existing enhancement request. I would close this one as a duplicate and suggest that you watch https://github.com/SAP/ui5-language-assistant/issues/520 for updates

**Closed by MN-public** 2023-03-08 13:15 UTC
Labels: enhancement
