### ISSUE TITLE
Tooltip property validation 

### ISSUE THREAD

**Issue by mateusz-matyjaszczyk** [SAP/ui5-language-assistant#707] opened 2024-04-22 06:48 UTC
Hey,

The code is working perfectly fine but it is showing an error "Mandatory property path must be defined"
![CleanShot 2024-04-22 at 13 48 22](https://github.com/SAP/ui5-language-assistant/assets/26802754/ff3b5c9b-5f24-4ce8-baf2-829b2f28ceca)
![CleanShot 2024-04-22 at 13 48 31](https://github.com/SAP/ui5-language-assistant/assets/26802754/af931550-e0c5-4e60-b047-79bab1662085)

**Comment by marufrasully** [comment] 2024-04-23 12:31
Dear @mateusz-matyjaszczyk,

thanks for reporting this issue. The issue is fixed and can be test with `.vsix` from https://github.com/SAP/ui5-language-assistant/releases/tag/v4.0.61. This fix will be part of up coming release.

Thanks and best regards

**Comment by MN-public** [comment] 2024-05-13 09:29
Fix is provided, closing the issue

**Closed by MN-public** 2024-05-13 09:29 UTC
