### ISSUE TITLE
manifest.json auto-complete for routing config shows viewPath instead of path

### ISSUE THREAD

**Issue by sagedev2k16** [SAP/ui5-language-assistant#691] opened 2024-02-04 17:27 UTC
Hi,

The auto-complete is giving "viewPath" as suggestion in manifest.json "routing" config instead of "path". I am using it with ui5 cli version 3.2.0 and OpenUI5 version 1.120.0

**This works**:
![image](https://github.com/SAP/ui5-language-assistant/assets/97039097/8eeadff0-c524-4ee4-9ed6-279d30710e7c)

**This doesn't work**:
![image](https://github.com/SAP/ui5-language-assistant/assets/97039097/ee251841-4ead-4cd0-bafd-e439c150e591)

UI5 documentation also mentions to use "path" in router config.
![image](https://github.com/SAP/ui5-language-assistant/assets/97039097/85d558d7-01a2-4244-89c3-e89ea91b3cad)

**Documentation link**: [sap.m.Router](https://sapui5.hana.ondemand.com/#/api/sap.m.routing.Router%23constructor)

**Comment by marufrasully** [comment] 2024-02-21 15:19
@sagedev2k16 Thanks for reporting this issue. The issue will be fixed and will be averrable starting on 21.03.2024. After cross checking the functionality, please close this issue if every thing is fine.

Thanks and regards

**Comment by marufrasully** [comment] 2024-03-20 07:00
@sagedev2k16  We are sorry to inform you that the fixed will be available by end of April. Please check functionality by end of April and close issue if everything is file.

Thanks and regards

**Comment by marufrasully** [comment] 2024-04-23 12:28
Dear @sagedev2k16,

Thanks for reporting this issue. The issue is fixed. Please re-test it and close this issue if everything is working as expected for you.

Thanks and regards

**Comment by MN-public** [comment] 2024-05-13 09:31
The fix is provided, closing the issue. @sagedev2k16 feel free to reopen if you still have problems in the newest version.

**Closed by MN-public** 2024-05-13 09:31 UTC
